In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
print(arr1.shape)

(5,)


In [4]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([10, 20, 30, 40, 50])
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]


In [11]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [12]:
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [13]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr[1:,2:4])


[[ 7  8]
 [11 12]]


In [ ]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
